/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ThreatRegistry } from './ThreatRegistry.js';
export * as factories from './factories/index.js';
export { ThreatRegistry__factory } from './factories/ThreatRegistry__factory.js';