/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ThreatRegistryInterface extends Interface {
    getFunction(nameOrSignature: "THRESHOLD" | "approveThreat" | "isBlacklisted" | "rejectThreat" | "submitThreat" | "threats" | "validators" | "voted"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ThreatApproved" | "ThreatConfirmed" | "ThreatRejected" | "ThreatSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'THRESHOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveThreat', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isBlacklisted', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'rejectThreat', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'submitThreat', values: [BytesLike, BytesLike, BytesLike, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'threats', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'validators', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'voted', values: [BytesLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'THRESHOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveThreat', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isBlacklisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectThreat', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitThreat', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'threats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validators', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voted', data: BytesLike): Result;
  }

  
    export namespace ThreatApprovedEvent {
      export type InputTuple = [threatId: BytesLike, validator: AddressLike, approveCount: BigNumberish];
      export type OutputTuple = [threatId: string, validator: string, approveCount: bigint];
      export interface OutputObject {threatId: string, validator: string, approveCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ThreatConfirmedEvent {
      export type InputTuple = [threatId: BytesLike, urlHash: BytesLike, apkHash: BytesLike];
      export type OutputTuple = [threatId: string, urlHash: string, apkHash: string];
      export interface OutputObject {threatId: string, urlHash: string, apkHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ThreatRejectedEvent {
      export type InputTuple = [threatId: BytesLike, validator: AddressLike, rejectCount: BigNumberish];
      export type OutputTuple = [threatId: string, validator: string, rejectCount: bigint];
      export interface OutputObject {threatId: string, validator: string, rejectCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ThreatSubmittedEvent {
      export type InputTuple = [threatId: BytesLike];
      export type OutputTuple = [threatId: string];
      export interface OutputObject {threatId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ThreatRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ThreatRegistry;
    waitForDeployment(): Promise<this>;

    interface: ThreatRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    approveThreat: TypedContractMethod<
      [_threatId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    isBlacklisted: TypedContractMethod<
      [_threatId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    rejectThreat: TypedContractMethod<
      [_threatId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitThreat: TypedContractMethod<
      [_urlHash: BytesLike, _apkHash: BytesLike, _evidenceHash: BytesLike, _c2: string, _riskScore: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    threats: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, string, string, bigint, bigint, bigint, bigint, bigint] & {urlHash: string, apkHash: string, evidenceHash: string, c2: string, riskScore: bigint, approveCount: bigint, rejectCount: bigint, status: bigint, createdAt: bigint }],
      'view'
    >
    

    
    validators: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    voted: TypedContractMethod<
      [arg0: BytesLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approveThreat'): TypedContractMethod<
      [_threatId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isBlacklisted'): TypedContractMethod<
      [_threatId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'rejectThreat'): TypedContractMethod<
      [_threatId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitThreat'): TypedContractMethod<
      [_urlHash: BytesLike, _apkHash: BytesLike, _evidenceHash: BytesLike, _c2: string, _riskScore: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'threats'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, string, string, bigint, bigint, bigint, bigint, bigint] & {urlHash: string, apkHash: string, evidenceHash: string, c2: string, riskScore: bigint, approveCount: bigint, rejectCount: bigint, status: bigint, createdAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'validators'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'voted'): TypedContractMethod<
      [arg0: BytesLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'ThreatApproved'): TypedContractEvent<ThreatApprovedEvent.InputTuple, ThreatApprovedEvent.OutputTuple, ThreatApprovedEvent.OutputObject>;
getEvent(key: 'ThreatConfirmed'): TypedContractEvent<ThreatConfirmedEvent.InputTuple, ThreatConfirmedEvent.OutputTuple, ThreatConfirmedEvent.OutputObject>;
getEvent(key: 'ThreatRejected'): TypedContractEvent<ThreatRejectedEvent.InputTuple, ThreatRejectedEvent.OutputTuple, ThreatRejectedEvent.OutputObject>;
getEvent(key: 'ThreatSubmitted'): TypedContractEvent<ThreatSubmittedEvent.InputTuple, ThreatSubmittedEvent.OutputTuple, ThreatSubmittedEvent.OutputObject>;

    filters: {
      
      'ThreatApproved(bytes32,address,uint8)': TypedContractEvent<ThreatApprovedEvent.InputTuple, ThreatApprovedEvent.OutputTuple, ThreatApprovedEvent.OutputObject>;
      ThreatApproved: TypedContractEvent<ThreatApprovedEvent.InputTuple, ThreatApprovedEvent.OutputTuple, ThreatApprovedEvent.OutputObject>;
    

      'ThreatConfirmed(bytes32,bytes32,bytes32)': TypedContractEvent<ThreatConfirmedEvent.InputTuple, ThreatConfirmedEvent.OutputTuple, ThreatConfirmedEvent.OutputObject>;
      ThreatConfirmed: TypedContractEvent<ThreatConfirmedEvent.InputTuple, ThreatConfirmedEvent.OutputTuple, ThreatConfirmedEvent.OutputObject>;
    

      'ThreatRejected(bytes32,address,uint8)': TypedContractEvent<ThreatRejectedEvent.InputTuple, ThreatRejectedEvent.OutputTuple, ThreatRejectedEvent.OutputObject>;
      ThreatRejected: TypedContractEvent<ThreatRejectedEvent.InputTuple, ThreatRejectedEvent.OutputTuple, ThreatRejectedEvent.OutputObject>;
    

      'ThreatSubmitted(bytes32)': TypedContractEvent<ThreatSubmittedEvent.InputTuple, ThreatSubmittedEvent.OutputTuple, ThreatSubmittedEvent.OutputObject>;
      ThreatSubmitted: TypedContractEvent<ThreatSubmittedEvent.InputTuple, ThreatSubmittedEvent.OutputTuple, ThreatSubmittedEvent.OutputObject>;
    
    };
  }